hmcts/vh-infra-core

azure-pipelines.yaml, config/terraform/application/vars/video-hearing-core/demo.tfvars, config/terraform/application/vars/video-hearing-core/dev.tfvars, config/terraform/application/vars/video-hearing-core/ithc.tfvars, config/terraform/application/vars/video-hearing-core/prod.tfvars, config/terraform/application/vars/video-hearing-core/sbox.tfvars, config/terraform/application/vars/video-hearing-core/stg.tfvars, config/terraform/application/vars/video-hearing-core/test.tfvars, config/terraform/application/vars/video-hearing-wowza/demo.tfvars, config/terraform/application/vars/video-hearing-wowza/dev.tfvars, config/terraform/application/vars/video-hearing-wowza/ithc.tfvars, config/terraform/application/vars/video-hearing-wowza/prod.tfvars, config/terraform/application/vars/video-hearing-wowza/sbox.tfvars, config/terraform/application/vars/video-hearing-wowza/stg.tfvars, config/terraform/application/vars/video-hearing-wowza/test.tfvars, pipeline-steps/deploy-service-elevated.yaml, pipeline-steps/keyvault-read.yaml, pipeline-steps/vh-tenant-replacement.yaml, terraform/video-hearing-core/00-init.tf
N/A
Inital commit for pipeline set-up
```
[ ] Yes
[X] No
```
=> initial set-up

azure-pipelines.yaml
N/A
wowza removal for testing
```
[ ] Yes
[X] No
```
=> removed wowza block for now

azure-pipelines.yaml, pipeline-steps/deploy-service-elevated.yaml, pipeline-steps/destroy-service-elevated.yaml, terraform/10-video-hearing-wowza/00-init.tf
N/A
Mostly adding a destory stage for use via ADO, needed it to destroy and recreate the current infra using the correct state files. All envs have their own state file in the HMCTS-CONTROL sub under a azure-control-<ENV>-rg resource group. 
```
[ ] Yes
[X] No
```
=> Backend fixes

azure-pipelines.yaml, pipeline-steps/terraform-validate.yaml, terraform/09-video-hearing-core/11-inputs-default.tf, terraform/09-video-hearing-core/20-main.tf, terraform/09-video-hearing-core/modules/AppConfiguration/main.tf, terraform/09-video-hearing-core/modules/AppReg/main.tf, terraform/09-video-hearing-core/modules/KeyVaults/main.tf, terraform/09-video-hearing-core/modules/Monitoring/main.tf, terraform/09-video-hearing-core/modules/SignalR/main.tf, terraform/09-video-hearing-core/modules/VHDataServices/main.tf, terraform/09-video-hearing-core/modules/redis/11-redis-cache.tf
https://tools.hmcts.net/jira/browse/VIH-8586
Made changes required to pass TFSec checks and try and implement better security practice in terraform files where possible. Also added #tfsec:ignore rules to avoid changes that would break the pipelines. 
```
[ ] Yes
[x ] No
```
=> Vih 8586 tf sec

azure-pipelines.yaml, pipeline-steps/destroy-service-elevated.yaml, terraform/09-video-hearing-core/20-main.tf, terraform/09-video-hearing-core/modules/PrivateEndpoint/main.tf
N/A
Very minor changes to the Stage names to allow the destroy bit to work again
Also added the tagging module to the Private Endpoints 
```
[ ] Yes
[X] No
```
=> Infra destroy fixes

terraform/09-video-hearing-core/00-init.tf, terraform/09-video-hearing-core/11-inputs-default.tf, terraform/09-video-hearing-core/12-interpolated-defaults.tf, terraform/09-video-hearing-core/20-main.tf, terraform/09-video-hearing-core/modules/DnsZone/inputs.tf, terraform/09-video-hearing-core/modules/PrivateEndpoint/inputs.tf, terraform/09-video-hearing-core/modules/PrivateEndpoint/main.tf, terraform/09-video-hearing-core/modules/PrivateEndpoint/outputs.tf, terraform/10-video-hearing-wowza/20-main.tf, terraform/10-video-hearing-wowza/modules/wowza/_inputs.tf, terraform/10-video-hearing-wowza/modules/wowza/private_endpoint.tf
https://tools.hmcts.net/jira/browse/VIH-8699
Added DNS config tothe infra-core endpoints
```
[ ] Yes
[X] No
```
=> ViH 8699 endpoint dns

terraform/09-video-hearing-core/modules/KeyVaults/main.tf
N/A
Added the reader role to the kvuser MI
```
[ ] Yes
[X] No
```
=> App kv reader role

.gitignore, azure-pipelines-nightly.yaml, pipeline-steps/keyvault-read.yaml, pipeline-steps/tfplan-drift-check.yaml
https://tools.hmcts.net/jira/browse/VIH-7496
Created a scheduled pipeline to ensure that our environments that are controlled by Terraform do not drift from the Terraform stored in git. It runs a 'Terraform show' command and will send an alert to the # vh-alerts slack channel. Does not run against SBOX.
Pipeline currently runs weekday evenings at 9pm, plus on the first of the month.
```
[ ] Yes
[x ] No
```
=> Vih 7496 create nightly plan pipeline

.gitignore, terraform/09-video-hearing-core/11-inputs-default.tf, terraform/09-video-hearing-core/12-interpolated-defaults.tf, terraform/09-video-hearing-core/20-main.tf, terraform/09-video-hearing-core/modules/PrivateEndpoint/inputs.tf, terraform/09-video-hearing-core/modules/PrivateEndpoint/main.tf, terraform/10-video-hearing-wowza/.terraform.lock.hcl, terraform/10-video-hearing-wowza/modules/wowza/_providers.tf, terraform/10-video-hearing-wowza/modules/wowza/lb-public.tf, terraform/10-video-hearing-wowza/modules/wowza/lb.tf
Add the Private Endpoint DNS Link for all resources
```
[ ] Yes
[ x ] No
```
=> Add the Private Endpoint DNS Link for all resources

terraform/09-video-hearing-core/20-main.tf, terraform/09-video-hearing-core/modules/AppConfiguration/main.tf, terraform/09-video-hearing-core/modules/AppConfiguration/outputs.tf, terraform/09-video-hearing-core/modules/KeyVaults/Secrets/main.tf, terraform/09-video-hearing-core/modules/KeyVaults/Secrets/variables.tf, terraform/09-video-hearing-core/modules/KeyVaults/inputs.tf, terraform/09-video-hearing-core/modules/KeyVaults/main.tf, terraform/09-video-hearing-core/modules/Monitoring/main.tf, terraform/09-video-hearing-core/modules/Monitoring/outputs.tf, terraform/09-video-hearing-core/modules/PrivateEndpoint/main.tf, terraform/09-video-hearing-core/modules/SignalR/inputs.tf, terraform/09-video-hearing-core/modules/SignalR/main.tf, terraform/09-video-hearing-core/modules/SignalR/outputs.tf, terraform/09-video-hearing-core/modules/VHDataServices/main.tf, terraform/09-video-hearing-core/modules/VHDataServices/outputs.tf, terraform/09-video-hearing-core/modules/redis/01-inputs-required.tf, terraform/09-video-hearing-core/modules/redis/03-interpolated-defaults.tf, terraform/09-video-hearing-core/modules/redis/11-redis-cache.tf, terraform/09-video-hearing-core/modules/redis/outputs.tf
Remove Dependencies from within the Pipeline 
```
[ ] Yes
[ x ] No
```
=> Fix Dependencies within the Terraform

README.md, azure-pipelines.yaml, pipeline-steps/ado-vars-to-tf.yaml, pipeline-steps/ado-vars.yaml, pipeline-steps/deploy-service-elevated.yaml, terraform/09-video-hearing-core/10-inputs-required.tf, terraform/09-video-hearing-core/20-main.tf, terraform/09-video-hearing-core/modules/KeyVaults/outputs.tf
VIH-8950
- Get ADO Libraries into YAML
- Get ADO Libraries into JSON for TF format
- Inject into Terraform
- Terraform import secrets into Key Vaults
- Update Read Me
```
[ ] Yes
[ x ] No
```
=> VIH-8950 - Add ADO Libraries to the Key Vaults

azure-pipelines.infra-core.yaml, azure-pipelines.wowza.yaml, terraform/09-video-hearing-core/00-init.tf, terraform/09-video-hearing-core/10-inputs-required.tf, terraform/09-video-hearing-core/modules/AppReg/init.tf, terraform/09-video-hearing-core/modules/AppReg/inputs.tf, terraform/09-video-hearing-core/modules/AppReg/main.tf, terraform/09-video-hearing-core/modules/KeyVaults/Secrets/main.tf, terraform/09-video-hearing-core/modules/KeyVaults/main.tf, terraform/09-video-hearing-core/modules/VHDataServices/main.tf
VIH-7551
Automatically Assign AD Groups to App Regs
```
[ ] Yes
[ x ] No
```
=> VIH-7551 - Assign Groups to App Reg

azure-pipelines.wowza.yaml, config/terraform/application/vars/10-video-hearing-wowza/demo.tfvars, config/terraform/application/vars/10-video-hearing-wowza/dev.tfvars, config/terraform/application/vars/10-video-hearing-wowza/ithc.tfvars, config/terraform/application/vars/10-video-hearing-wowza/prod.tfvars, config/terraform/application/vars/10-video-hearing-wowza/sbox.tfvars, config/terraform/application/vars/10-video-hearing-wowza/stg.tfvars, config/terraform/application/vars/10-video-hearing-wowza/test.tfvars, terraform/10-video-hearing-wowza/10-inputs-required.tf, terraform/10-video-hearing-wowza/20-main.tf, terraform/10-video-hearing-wowza/cloudconfig.tpl, terraform/10-video-hearing-wowza/modules/wowza/_inputs.tf, terraform/10-video-hearing-wowza/modules/wowza/private_endpoint.tf, terraform/10-video-hearing-wowza/modules/wowza/vm_automation.tf, terraform/10-video-hearing-wowza/modules/wowza/vm_base.tf
VIH-8810
Check the Wowza is peered to the hub
Fix TF errors
Correct implementation of Certificates
```
[ x ] Yes
[ ] No
```
=> VIH-8810 wowza peering and fixes

config/terraform/application/vars/10-video-hearing-wowza/demo.tfvars, config/terraform/application/vars/10-video-hearing-wowza/dev.tfvars, config/terraform/application/vars/10-video-hearing-wowza/ithc.tfvars, config/terraform/application/vars/10-video-hearing-wowza/prod.tfvars, config/terraform/application/vars/10-video-hearing-wowza/sbox.tfvars, config/terraform/application/vars/10-video-hearing-wowza/stg.tfvars, config/terraform/application/vars/10-video-hearing-wowza/test.tfvars, terraform/09-video-hearing-core/modules/AppReg/main.tf, terraform/09-video-hearing-core/modules/KeyVaults/main.tf
Add Tenant ID secret and DTS SDS Dev access
```
[ ] Yes
[ x ] No
```
=> Add Tenant ID secret and DTS SDS Dev access

terraform/09-video-hearing-core/20-main.tf, terraform/09-video-hearing-core/modules/AppReg/main.tf
Add tenant id for AAD
```
[ ] Yes
[ x ] No
```
=> Add tenant id

pipeline-steps/terraform-plan-apply.yaml
Unlock resource groups before deployment
```
[ ] Yes
[ x ] No
```
=> Add unlock task

terraform/10-video-hearing-wowza/cloudconfig.tpl
[VIH](https://tools.hmcts.net/jira/browse/VIH-9153)
Added TLSv1.2 to wowza REST api as part of ITHC recommendations
```
[ ] Yes
[X ] No
```
=> Added TLSv1.2 to rest api in wowza

pipeline-steps/terraform-plan-apply.yaml
VIH-8971
fix issues with pipeline flow on wowza
```
[ ] Yes
[ x ] No
```
=> VIH-8971 wowza settings

pipeline-steps/terraform-plan-apply.yaml
DB Access update for SDP
```
[ ] Yes
[ x ] No
```
=> DB Access update for SDP

pipeline-steps/az-ext-dynatrace-api.yaml, terraform/10-video-hearing-wowza/cloudconfig.tpl, terraform/10-video-hearing-wowza/modules/wowza/_providers.tf, terraform/10-video-hearing-wowza/modules/wowza/managed_identity.tf, terraform/10-video-hearing-wowza/modules/wowza/network.tf, terraform/10-video-hearing-wowza/modules/wowza/network_peering_vpn.tf, terraform/10-video-hearing-wowza/modules/wowza/network_vnet_link.tf, terraform/10-video-hearing-wowza/modules/wowza/vm_automation.tf, terraform/10-video-hearing-wowza/modules/wowza/vm_base.tf
VIH-8810
VNet peer to VPN VNet
VNet link to DNS
correct wowza installation
Correct Dynatrace setting
Add SSH exception rule.
```
[ ] Yes
[ x ] No
```
=> VIH-8810 - Enable private DNS requests

pipeline-steps/terraform-plan-apply.yaml, terraform/10-video-hearing-wowza/modules/wowza/network.tf
[VIH-9148](https://tools.hmcts.net/jira/browse/VIH-9148)
correct port range
only run SQL access on core infra
```
[ ] Yes
[ x ] No
```
=> VIH-9148 - Correct Wowza DNS Range

azure-pipelines.wowza.yaml, pipeline-steps/terraform-plan.yaml, terraform/10-video-hearing-wowza/modules/wowza/vm_base.tf
Add Step to approve Wowza Terms of Image
```
[ ] Yes
[ x ] No
```
=> Add wowza approval

terraform/10-video-hearing-wowza/modules/wowza/network_vnet_link.tf
Correct domain name for wowza
```
[ ] Yes
[ x ] No
```
=> Correct domain name for wowza

config/pipeline/vars/wowza/prod.yaml, config/pipeline/vars/wowza/stg.yaml, pipeline-steps/az-ext-dynatrace-api.yaml, pipeline-steps/terraform-plan-apply.yaml
Fix Dynatrace extension
Exclude SQL from Wowza run
```
[ ] Yes
[ x ] No
```
=> Fix Wowza pipeline

pipeline-steps/terraform-plan-apply.yaml, terraform/09-video-hearing-core/20-main.tf, terraform/09-video-hearing-core/modules/AppReg/main.tf
VIH-9103
Update Storage Account to the shared module
Add storage account secrets to the vault.
```
[ ] Yes
[ x ] No
```
=> VIH-9103 - Add secrets

terraform/09-video-hearing-core/10-inputs-required.tf, terraform/09-video-hearing-core/modules/AppReg/main.tf
amend staging URL's
```
[ ] Yes
[ x ] No
```
=> VIH-999 - amend staging URL's

azure-pipelines.infra-core.yaml, azure-pipelines.wowza.yaml, pipeline-steps/terraform-plan-apply.yaml
VIH-9193
Add Test environment to the core infra
Add environment dependencies for each pipeline
```
[ ] Yes
[ x ] No
```
=> VIH-9193 - Add Test for Core and add dependencies

terraform/10-video-hearing-wowza/modules/wowza/_inputs.tf, terraform/10-video-hearing-wowza/modules/wowza/vm_base.tf
VIH-9121
extend os disk and remove additional disk
```
[ ] Yes
[ x ] No
```
=> VIH-9121 - extend os disk and remove additional disk

terraform/10-video-hearing-wowza/modules/wowza/secrets.tf
VIH-8972
Add Wowza REST endpoint
```
[ ] Yes
[ x ] No
```
=> VIH-8972 - Add Wowza REST endpoint

terraform/09-video-hearing-core/20-main.tf
VIH-9103
Add Web Jobs Storage Account Connection String
```
[ ] Yes
[ x ] No
```
=> VIH-9103 -  Add Web Jobs Storage Account Connection String

config/terraform/application/vars/10-video-hearing-wowza/dev.tfvars, config/terraform/application/vars/10-video-hearing-wowza/prod.tfvars, config/terraform/application/vars/10-video-hearing-wowza/sbox.tfvars, config/terraform/application/vars/10-video-hearing-wowza/stg.tfvars, config/terraform/application/vars/10-video-hearing-wowza/test.tfvars, pipeline-steps/ado-vars.yaml, terraform/10-video-hearing-wowza/10-inputs-required.tf, terraform/10-video-hearing-wowza/20-main.tf, terraform/10-video-hearing-wowza/modules/wowza/_inputs.tf, terraform/10-video-hearing-wowza/modules/wowza/_providers.tf, terraform/10-video-hearing-wowza/modules/wowza/network_routing.tf
VIH-9148
Add Route Table to AKS
```
[ ] Yes
[ x ] No
```
=> VIH-9148 - Add Route Table

terraform/09-video-hearing-core/20-main.tf
VIH-9209
correct private link dns a record names
```
[ ] Yes
[ x ] No
```
=> VIH-9209 - correct private link dns a record names

config/terraform/application/vars/10-video-hearing-wowza/demo.tfvars, config/terraform/application/vars/10-video-hearing-wowza/ithc.tfvars, terraform/10-video-hearing-wowza/modules/wowza/network_routing.tf
VIH-9148
Add missing routing
```
[ ] Yes
[ x ] No
```
=> VIH-9148 - Add missing routing

terraform/09-video-hearing-core/modules/VHDataServices/main.tf
VIH-9120
add keda MI to Service Bus
```
[ ] Yes
[x  ] No
```
=> VIH-9120 - Add KEDA MI to Service Bus

terraform/10-video-hearing-wowza/modules/wowza/secrets.tf
VIH-9236
Add missing variables for wowza
```
[ ] Yes
[ x ] No
```
=> VIH-9236 - Add missing variables for wowza

terraform/09-video-hearing-core/10-inputs-required.tf, terraform/09-video-hearing-core/modules/AppReg/main.tf
VIH-9236
Change App Regs from Web to SPA
```
[ ] Yes
[ x ] No
```
=> VIH-9236 - Change App Regs from Web to SPA

pipeline-steps/ado-vars.yaml
VIH-9236
Add common group
```
[ ] Yes
[ x ] No
```
=> VIH-9236 - Add common group

terraform/09-video-hearing-core/modules/AppReg/main.tf
change secret from stg to staging 
```
[ ] Yes
[ x] No
```
=> VIH-9999 - Patch 

terraform/09-video-hearing-core/10-inputs-required.tf, terraform/09-video-hearing-core/20-main.tf, terraform/09-video-hearing-core/modules/AppReg/inputs.tf, terraform/09-video-hearing-core/modules/AppReg/main.tf
VIH-9236
Add API scopes
```
[ ] Yes
[ x ] No
```
=> VIH-9236 - Add API scopes

terraform/09-video-hearing-core/10-inputs-required.tf
VIH-9236
Add scope for Video Web
```
[ ] Yes
[ x ] No
```
=> VIH-9236 - Add scope for Video Web

pipeline-steps/az-ext-dynatrace-api.yaml, pipeline-steps/az-ext-oms.yaml, pipeline-steps/check-state.yaml, terraform/09-video-hearing-core/20-main.tf
Correct the tagging for application
Remove the two resource no one wants to say we need. only commented out incase it get discovered we do need them.
```
[ ] Yes
[ x ] No
```
=> Correct Tagging and remove unneeded resources

terraform/09-video-hearing-core/20-main.tf, terraform/09-video-hearing-core/modules/KeyVaults/inputs.tf, terraform/09-video-hearing-core/modules/KeyVaults/main.tf, terraform/09-video-hearing-core/modules/KeyVaults/outputs.tf, terraform/09-video-hearing-core/modules/VHDataServices/main.tf, terraform/10-video-hearing-wowza/modules/wowza/managed_identity.tf, terraform/10-video-hearing-wowza/modules/wowza/secrets.tf
VIH-9999 - Create Generic MI
VIH-9999 - Create Generic MI
```
[ ] Yes
[x ] No
```
=> VIH-9999 - Create Generic MI

terraform/10-video-hearing-wowza/cloudconfig.tpl
VIH-9243
Check for any small files
```
[ ] Yes
[ x ] No
```
=> VIH-9243 - Add 1MB file checks

terraform/09-video-hearing-core/20-main.tf, terraform/10-video-hearing-wowza/modules/wowza/network.tf
[VIH-9364](https://tools.hmcts.net/jira/browse/VIH-9364)
Amend Private Endpoint DNS.
```
[ ] Yes
[ x ] No
```
=> VIH-9999 - amend DNS

terraform/09-video-hearing-core/10-inputs-required.tf, terraform/09-video-hearing-core/20-main.tf, terraform/09-video-hearing-core/modules/AppReg/inputs.tf, terraform/09-video-hearing-core/modules/AppReg/main.tf
VIH-9296 
Add vh-user-api to HelpDeskAdmins 
```
[ ] Yes
[ x ] No
```
=> VIH-9296 - Add vh-user-api to HelpDeskAdmins 

terraform/10-video-hearing-wowza/cloudconfig.tpl
https://tools.hmcts.net/jira/browse/VIH-9153
Added CVP tuning to VH in cloudconfig.tpl.
```
[ ] Yes
[ X] No
```
=> Vih 9153 add cvp tuning to vh wowza

terraform/10-video-hearing-wowza/modules/wowza/network.tf, terraform/10-video-hearing-wowza/modules/wowza/network_vnet_link.tf
VIH-8976
Add DNs link to platform.hmcts.net for splunk DNS
Add outbound rules to allow splunk outbound
```
[ ] Yes
[ x ] No
```
=> VIH-8976 - Add dns link and outbound rule

terraform/10-video-hearing-wowza/modules/wowza/network_vnet_link.tf
VIH-8976
platform.hmcts.net is already linked by code above, so it is creating a duplicate.
removing the requirement from the new link section
```
[ ] Yes
[ x ] No
```
=> VIH-8976 - Splunk remove dns link for production

terraform/09-video-hearing-core/modules/Monitoring/alert_cron_jobs.tf
VIH-9249
Add Cron Job Monitoring
```
[ ] Yes
[ x ] No
```
=> VIH-9249 - Add Cron Job Monitoring

config/terraform/application/vars/10-video-hearing-wowza/dev.tfvars, terraform/10-video-hearing-wowza/10-inputs-required.tf, terraform/10-video-hearing-wowza/20-main.tf, terraform/10-video-hearing-wowza/modules/wowza/_inputs.tf
VIH-9385
Pass schedules var in, missing from wowza
```
[ ] Yes
[ x ] No
```
=> VIH-9385 - Pass schedules var in

terraform/10-video-hearing-wowza/cloudconfig.tpl, terraform/10-video-hearing-wowza/modules/wowza/vm_automation.tf
VIH-9999
Amend Wowza Config
```
[ ] Yes
[x ] No
```
=> VIH-9999 - Amend Wowza Config

azure-pipelines.wowza.yaml, pipeline-steps/terraform-plan-apply.yaml, terraform/10-video-hearing-wowza/20-main.tf, terraform/10-video-hearing-wowza/modules/wowza/automation_account.tf
VIH-9435 
VIH-9435 - Change VM Count for Wowza, Remove Daily Restarts
```
[ ] Yes
[x  ] No
```
=> VIH-9435 - Change VM Count for Wowza & Remove Daily Restarts

terraform/10-video-hearing-wowza/cloudconfig.tpl
Amend Wowza App Changes
```
[ ] Yes
[x] No
```
=> VIH-9999 - Amend Wowza App Changes

config/terraform/application/vars/10-video-hearing-wowza/dev.tfvars, config/terraform/application/vars/10-video-hearing-wowza/prod.tfvars, config/terraform/application/vars/10-video-hearing-wowza/stg.tfvars, config/terraform/application/vars/10-video-hearing-wowza/test.tfvars
VIH-8976
Add Routes for Splunk Forwarder
```
[ ] Yes
[ x ] No
```
=> VIH-8976 - Add Routes for Splunk Forwarder

azure-pipelines.infra-core.yaml, azure-pipelines.wowza.yaml, terraform/09-video-hearing-core/modules/Monitoring/alert_cron_jobs.tf
N/A
Change alert query to reflect changes in Scheduler jobs logging and deploy alert to prod env only
```
[ ] Yes
[ X] No
```
=> VIH-9999 update scheduler jobs alerts in sds

terraform/09-video-hearing-core/modules/Monitoring/alert_cron_jobs.tf
N/A
Include vh-hearings-allocations-job and fix duplicate job
```
[ ] Yes
[X ] No
```
=> VIH-9999 Include hearing allocations in cron jobs

config/terraform/application/vars/10-video-hearing-wowza/prod.tfvars, terraform/09-video-hearing-core/10-inputs-required.tf, terraform/09-video-hearing-core/20-main.tf
[VIH-9502](https://tools.hmcts.net/jira/browse/VIH-9502)
Updating the size of the databases in production
```
[ ] Yes
[X] No
```
=> VIH-9502 Update production database sizes

config/terraform/application/vars/09-video-hearing-core/prod.tfvars, config/terraform/application/vars/10-video-hearing-wowza/prod.tfvars
[VIH-9502](https://tools.hmcts.net/jira/browse/VIH-9502)
Moving override to correct tfvars file
```
[ ] Yes
[X] No
```
=> VIH-9502 Moving override to correct tfvars

terraform/09-video-hearing-core/modules/Monitoring/alert_wowza.tf
https://tools.hmcts.net/jira/browse/VIH-9507
Create load balancer alerts for vh infra wowza prod
```
[ ] Yes
[ X] No
```
=> VIH-9507 Create load balancer alerts for vh-infra-wowza-prod

terraform/09-video-hearing-core/modules/KeyVaults/reporting.tf
Add VH Reporting MI and access to KV
```
[ ] Yes
[ x ] No
```
=> VIH-9523 - Add VH Reporting MI and access to KV

terraform/09-video-hearing-core/modules/AppReg/main.tf, terraform/09-video-hearing-core/modules/SignalR/main.tf
Ignore changes to SPA
```
[ ] Yes
[x ] No
```
=> VIH-9999 - Ignore changes to SPA

terraform/10-video-hearing-wowza/cloudconfig.tpl
https://tools.hmcts.net/jira/browse/VIH-9509
Adds a bash script to cloudinit.tpl to check every 15 minutes that the Azure storage is mounted
```
[ ] Yes
[X ] No
```
=> VIH-9509 check for blob every 15 min - alert if not found

terraform/10-video-hearing-wowza/modules/wowza/wowza_lb_alerts.tf
N/A
Added tags to Load Balancer alerts in accordance with HMCTS policy
```
[ ] Yes
[ X] No
```
=> VIH-9999 Add tags to LB alerts

azure-pipelines-nightly.yaml, azure-pipelines.infra-core.yaml, azure-pipelines.wowza.yaml, azure-pipelines.yaml
https://tools.hmcts.net/jira/browse/VIH-9544
Updating VMimage to 22.04 
```
[ ] Yes
[X ] No
```
=> VIH-9544 - update vm image in pipeline

terraform/10-video-hearing-wowza/modules/wowza/network.tf
VIH-9549 - Add Dynatrace IP Addresses
VIH-9549 - Add Dynatrace IP Addresses
```
[ ] Yes
[ x ] No
```
=> VIH-9549 - Add Dynatrace IP Addresses for Prod

azure-pipelines.yaml, terraform/20-main.tf
VIH-9609 - Add AA & Runbook
VIH-9609 - Add AA & Runbook
```
[ ] Yes
[ x ] No
```
=> VIH-9609 - Add AA Runbook

azure-pipelines.yaml
https://tools.hmcts.net/jira/browse/VIH-9650?filter=-1
Remove Test Environment from SDS.
```
[ ] Yes
[X ] No
```
=> VIH-9650 remove test environment from SDS

azure-pipelines.destroy.yaml, pipeline-steps/terraform-plan-apply.yaml, pipeline-steps/terraform-plan.yaml
VIH-9677 - add destroy support
VIH-9677 - add destroy support
```
[ ] Yes
[ x ] No
```
=> VIH-9677 - add destroy support

pipeline-steps/ado-vars.yaml, terraform/modules/SignalR/main.tf
VIH-9506 - add QuickLinks 
```
[ ] Yes
[ x ] No
```
=> VIH-9506 - add QuickLinks 

azure-pipelines.yaml
N/A
Add ITHC environment to VH
```
[ ] Yes
[X ] No
```
=> VIH-9999 add ITHC

terraform/20-main.tf
https://tools.hmcts.net/jira/browse/VIH-9778
Change the dynatrace_runbook module to v.1.0.1
```
[ ] Yes
[X ] No
```
=> VIH-9778 Change module version number

terraform/10-inputs-required.tf
VIH-9795 - Remove Test DBs
```
[ ] Yes
[ x ] No
```
=> VIH-9795 - Remove Test DBs

pipeline-steps/ado-vars.yaml
https://tools.hmcts.net/jira/browse/VIH-9868
Add logic to pick up different var lib if prod or non-prod
```
[ ] Yes
[X] No
```
=> VIH-9868 Add logic for scheduler job env

azure-pipelines.yaml, terraform/20-main.tf
https://tools.hmcts.net/jira/browse/VIH-9912
Add Test Environment
```
[ ] Yes
[X] No
```
=> VIH-9912 Add-Test-Environment

config/terraform/application/vars/test.tfvars
https://tools.hmcts.net/jira/browse/VIH-9912
Updating database in test.tfvars 
```
[ ] Yes
[x] No
```
=> VIH-9912 Updating database on test

terraform/20-main.tf, terraform/modules/Monitoring/outputs.tf
Adding ai connection string
```
[ ] Yes
[] No
```
=> VIH-0000 Adding ai connection string

.github/workflows/main.yml
https://tools.hmcts.net/jira/browse/VIH-10014
Update regex in order to create PR
[ ] Yes
[x] No
```
=> VIH-10014 Regex-Update-PR

.github/workflows/main.yml
https://tools.hmcts.net/jira/browse/VIH-10014
Update regex in order to create PR
```
[ ] Yes
[x] No
```
=> VIH-0000 regex

.github/workflows/main.yml, config/terraform/application/vars/dev.tfvars
https://tools.hmcts.net/jira/browse/VIH-10103
Updating dev environment db for vhvideo to be S2 50 DTUs. Also, updating the regex to allow new pr's to run successfully.
```
[ ] Yes
[x] No
```
=> VIH-10103 Updating vhvideo to S2

terraform/modules/redis/10-redis-inputs.tf
Update stg redis size to match current
```
[ ] Yes
[X] No
```
=> VIH-0000 Update 10-redis-inputs.tf

terraform/00-init.tf, terraform/20-main.tf, terraform/modules/KeyVaults/main.tf
[VIH-10233](https://tools.hmcts.net/jira/browse/VIH-10233)
```
[ ] Yes
[ ] No
```
=> VIH-10233 add policy for stg in dev akv

azure-pipeline.dbbackup.yaml, terraform/20-main.tf
[VIH-10320](https://tools.hmcts.net/jira/browse/VIH-10320)
```
[ ] Yes
[ ] No
```
=> VIH-10320 add prod env parameter and resource lock removal

terraform/modules/redis/10-redis-inputs.tf
=> update prod value

terraform/modules/VHDataServices/main.tf
=> Migrate service bus premium

config/terraform/application/vars/prod.tfvars, terraform/modules/VHDataServices/main.tf
=> Feature update servicebus - Added Code for Service Bus Premium Namespace, Changed vhvideo SKU to S6

terraform/modules/VHDataServices/main.tf
=> Updated service bus name

terraform/20-main.tf, terraform/modules/SignalR/inputs.tf, terraform/modules/SignalR/main.tf, terraform/modules/redis/10-redis-inputs.tf
=> Upgrade redis signal R

terraform/modules/VHDataServices/inputs.tf
=> Update inputs.tf added default to var.queue

terraform/modules/SignalR/main.tf, terraform/modules/VHDataServices/main.tf
=> Updated the capacity

terraform/import.tf
=> import formatted

terraform/import.tf
=> import the sbus and role assignment

terraform/20-main.tf
=> added import

terraform/20-main.tf
=> adding import

terraform/20-main.tf
=> Removing import commands 

terraform/modules/VHDataServices/main.tf
=> amended the code

terraform/modules/VHDataServices/outputs.tf
=> Fix sbus connection string 

terraform/00-init.tf
https://tools.hmcts.net/jira/browse/VIH-10991
skip_provider_registration needs to be implemented to bypass error
```
[ ] Yes
[x ] No
```
=> VIH-10991 fix infra core

README.md, azure-pipelines.yaml, config/terraform/application/vars/demo.tfvars, config/terraform/application/vars/dev.tfvars, config/terraform/application/vars/prod.tfvars, config/terraform/application/vars/test.tfvars, pipeline-steps/ado-vars-to-tf.yaml, pipeline-steps/keyvault-read.yaml, pipeline-steps/terraform-apply.yaml, pipeline-steps/terraform-plan-apply.yaml, pipeline-steps/terraform-plan.yaml, pipeline-steps/terraform-validate.yaml, pipeline-steps/vh-tenant-replacement.yaml, terraform/10-inputs-required.tf, terraform/20-main.tf, terraform/modules/Monitoring/main.tf, terraform/modules/SignalR/main.tf, terraform/modules/VHDataServices/main.tf
https://tools.hmcts.net/jira/browse/VIH-11092
Use external vh-setup repo for ADO library references instead of vh-key-vault-vars library
```
[ ] Yes
[x] No
```
=> VIH-11092 use ext repo for secrets

terraform/00-init.tf, terraform/20-main.tf, terraform/modules/Monitoring/main.tf, terraform/modules/SignalR/main.tf, terraform/modules/VHDataServices/main.tf, terraform/modules/redis/11-redis-cache.tf
https://tools.hmcts.net/jira/browse/VIH-11226
New perf-test container needs to be created for testing purposes
```
[ ] Yes
[x ] No
```
=> VIH-11226 Add perf test container

terraform/20-main.tf
https://tools.hmcts.net/jira/browse/VIH-11226
Change perf test container name
```
[ ] Yes
[x ] No
```
=> VIH-11226 Name change

azure-pipelines.yaml, terraform/modules/VHDataServices/main.tf
https://tools.hmcts.net/jira/browse/VIH-11261
Fixes premium_messaging_partitions Terraform plan drift in Prod
=> VIH-11261 fix premium_messaging_partitions issue

pipeline-steps/ado-vars.yaml, terraform/10-inputs-required.tf
https://tools.hmcts.net/jira/browse/VIH-11156
Remove Vh-test-api, bh-test-web dependencies 
```
[ ] Yes
[x ] No
```
=> VIH-11156 Remove test dependencies

pipeline-steps/ado-vars.yaml
https://tools.hmcts.net/jira/browse/VIH-11302
There are two keys/secrets in the FeatureFlags groups which are still needed. One pair for non-prod, one for prod
=> VIH-11302 Use FeatureFlags_Prod and Non-Prod groups
